cache:
  directories:
  - $HOME/.jdk
sudo: false
env:
  - EXPECTED_VERSION=1.8.0_74 JDKW_VERSION=8u74 JDKW_BUILD=b02 JDKW_VERBOSE=1
  - EXPECTED_VERSION=1.8.0_121 JDKW_VERSION=8u121 JDKW_BUILD=b13 JDKW_VERBOSE=1 JDKW_TOKEN=e9e7ea248e2c4826b92b3f075a80e441
  - EXPECTED_VERSION=1.6.0_38 JDKW_VERSION=6u38 JDKW_BUILD=b05 JDKW_VERBOSE=1
install: true
script:
  # Override the .jdkw file settings used by local builds
- ./jdk-wrapper.sh JDKW_VERSION=${JDKW_VERSION} JDKW_BUILD=${JDKW_BUILD} JDKW_TOKEN=${JDKW_TOKEN} javac -version
- if [ "$(./jdk-wrapper.sh JDKW_VERSION=${JDKW_VERSION} JDKW_BUILD=${JDKW_BUILD} JDKW_TOKEN=${JDKW_TOKEN} javac -version 2>&1 | tail -n 1)" != "javac ${EXPECTED_VERSION}" ]; then exit 1; fi;
